name: responder
namespace: ""
runtime: node
image: ""
imageDigest: ""
trigger: events
builder: default
builderMap:
  default: quay.io/boson/faas-nodejs-builder
volumes: []
envs:
- name: TELEGRAM_API_KEY
  value: '{{ env:TELEGRAM_API_KEY }}'
annotations: {}
options: {}
