name: processor
namespace: ""
runtime: quarkus
image: ""
imageDigest: ""
trigger: events
builder: quay.io/boson/faas-quarkus-jvm-builder
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
envVars:
  OCP_APIM_SUBSCRIPTION_KEY: "<YOUR SUBSCRIPTION KEY>"
